[[dependency]]
org = "ballerinax"
name = "slack"
version = "0.9.8"

[[dependency]]
org = "ballerina"
name = "websub"
version = "1.2.0-alpha8"

[[dependency]]
org = "ballerinax"
name = "github"
version = "0.99.14"

[[dependency]]
org = "ballerina"
name = "http"
version = "1.1.0-alpha8"
