[[dependency]]
org = "ballerina"
name = "http"
version = "1.1.0-alpha8"

[[dependency]]
org = "ballerina"
name = "regex"
version = "0.7.0-alpha8"

[[dependency]]
org = "ballerina"
name = "log"
version = "1.1.0-alpha8"

[[dependency]]
org = "ballerina"
name = "websub"
version = "1.2.0-alpha8"

[[dependency]]
org = "ballerina"
name = "os"
version = "0.8.0-alpha8"

[[dependency]]
org = "ballerina"
name = "url"
version = "1.1.0-alpha8"

[[dependency]]
org = "ballerina"
name = "crypto"
version = "1.1.0-alpha8"

[[dependency]]
org = "ballerina"
name = "io"
version = "0.6.0-alpha8"

[[dependency]]
org = "ballerina"
name = "mime"
version = "1.1.0-alpha8"

[[dependency]]
org = "ballerinax"
name = "github"
version = "0.99.14"

[[dependency]]
org = "ballerinax"
name = "twilio"
version = "0.99.8"
