[[dependency]]
org = "ballerina"
name = "io"
version = "0.6.0-alpha8"

[[dependency]]
org = "ballerina"
name = "log"
version = "1.1.0-alpha8"

[[dependency]]
org = "ballerina"
name = "http"
version = "1.1.0-alpha8"

[[dependency]]
org = "ballerinax"
name = "slack"
version = "0.9.8"

[[dependency]]
org = "ballerinax"
name = "sfdc"
version = "2.1.8"
